baseURL = "https://yoga-muenchen-bogenhausen.de"
languageCode = "de"
title = "Open Yoga MUC"

paginate = 100
preserveTaxonomyNames = true
pygmentsCodefences = true
pygmentsUseClasses = true
enableRobotsTXT = true
disableAliases = true
metaDataFormat = "yaml"

[params]
rssLimit = 100
description = "Yoga in MÃ¼nchen Bogenhausen"
authors = ["agobrecht"]

[permalinks]
artikel = "/:section/:year/:filename/"
rezepte = "/:section/:filename/"

[taxonomies]
schlagwort = "schlagwoerter"
rezeptart = "rezeptarten"
hauptzutat = "hauptzutaten"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]

[[menu.main]]
name = "Artikel"
weight = 40
identifier = "artikel"
url = "/artikel/"
[[menu.main]]
name = "Rezepte"
weight = 50
identifier = "rezepte"
url = "/rezepte/"
